#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
MANIFEST="$ROOT_DIR/tests/haskell_upstream/test_module_manifest.tsv"
OUT_RS="$ROOT_DIR/tests/pending_haskell_modules.rs"

if [[ ! -f "$MANIFEST" ]]; then
  echo "Missing test module manifest: $MANIFEST" >&2
  echo "Run scripts/update_porting_status.sh first." >&2
  exit 1
fi

{
  echo "// AUTO-GENERATED by scripts/generate_haskell_module_smoke_tests.sh"
  echo "// Smoke coverage for imported upstream Haskell test modules."
  echo "// These tests validate fixture presence/readability only."
  echo
  cat <<'RUST_HEADER'
fn has_content(s: &str) -> bool {
    !s.trim().is_empty()
}

RUST_HEADER
} > "$OUT_RS"

count=0
while IFS= read -r rel; do
  id="$(printf "%s" "$rel" \
    | tr '[:upper:]' '[:lower:]' \
    | sed -E 's#[^a-z0-9]+#_#g' \
    | sed -E 's#_+#_#g' \
    | sed -E 's#^_##; s#_$##')"
  include_path="haskell_upstream/tests/$rel"
  {
    echo "#[test]"
    echo "fn pending_module_${id}() {"
    echo "    let hs = include_str!(\"$include_path\");"
    echo "    assert!(has_content(hs), \"Haskell test fixture is empty: $include_path\");"
    echo "    assert!(hs.contains(\"module \"), \"Missing module declaration in $include_path\");"
    echo "}"
    echo
  } >> "$OUT_RS"
  count=$((count + 1))
done < "$MANIFEST"

echo "Wrote $OUT_RS with $count tests."
